include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

# Additional rules and analysis configurations to improve code quality
linter:
  rules:
    # Error rules
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_types_as_parameter_names
    - control_flow_in_finally
    - empty_statements
    - no_duplicate_case_values
    - throw_in_finally
    - valid_regexps

    # Style rules
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - avoid_bool_literals_in_conditional_expressions
    - avoid_implementing_value_types
    - avoid_redundant_argument_values
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - directives_ordering
    - package_api_docs
    - prefer_const_constructors
    - prefer_final_fields
    - prefer_final_locals
    - prefer_interpolation_to_compose_strings
    - prefer_null_aware_operators
    - sort_constructors_first
    - sort_pub_dependencies
    - unnecessary_parenthesis
    - use_full_hex_values_for_flutter_colors

analyzer:
  errors:
    # Treat missing documentation comments as hints rather than warnings
    # comment_references: info

    # Treat public API without documentation as a warning
    public_member_api_docs: warning
